package edu.kit.informatik.ui.parameter;

/**
 * Description of a parameter, a parameter includes a regex-pattern and a method to generate the correct data.
 * Note: Parameters should be when the data has been used.
 * @author uppyo
 * @version 1.0
 * @param <T> Data-Type of the object the parameter generates
 */
public interface Parameter <T>{

    /**
     * Get the regex-pattern of the parameter
     * @return regex-pattern as String
     */
    String getPattern();

    /**
     * Clear the stored data of the parameter
     */
    void clearParameter();

    /**
     * Set the parameter data to the specified object-type
     * @param value parsed input-string
     */
    void setValue(String value);

    /**
     * Get the current parameter-value
     * @return A object of the specified type, that was generated by input-data
     */
    T getValue();

    /**
     * Check if the parameter has generated an Object
     * @return True if a Object is stored in the parameter
     */
    boolean hasValue();
}
